ecommerce/cart_app/urls.py
from ecommerce import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'cart_app'
urlpatterns = [
    path('add/<int:product_id>/',views.add_Cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),
    path('fullremove/<int:product_id>',views.full_remove,name='full_remove'),

]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp/', include('ecommerceapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root = settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root = settings.MEDIA_ROOT)

ecommerce/ecommerceapp/urls.py
from ecommerce import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'ecommerceapp'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
path('<slug:c_slug>/<slug:product_slug>/',views.prodDetail,name='prodCatDetail')
]

ecommerce/search_app/urls.py
from ecommerce import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'search_app'
urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

ecommerce/cart_app/models.py
from django.db import models

# Create your models here.

from ecommerceapp.models import Product

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

ecommerce/ecommerceapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecommerceapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):

    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerceapp:prodCatDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_Cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))

    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product = product, cart= cart)
        if cart_item.quantity < cart_item.product.stock :
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity=1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass

    product_instance = cart_items.first().product
    c_slug = product_instance.category.slug
    product_slug = product_instance.slug

    product_detail_url = reverse('ecommerceapp:prodCatDetail',kwargs={'c_slug':c_slug,'product_slug':product_slug})
    return render(request,'cart.html',dict(cart_items = cart_items,total = total, counter = counter, product_detail_url=product_detail_url))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommerce/ecommerceapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from . models import Category,Product
# Create your views here.

def allProdCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug = c_slug)
        products_list = Product.objects.all().filter(category = c_page,available = True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except :
        page = 1
    try:
        products = paginator.page(page)
    except ( EmptyPage,InvalidPage ):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def prodDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})

ecommerce/search_app/views.py
from django.shortcuts import render
from ecommerceapp.models import Product,Category
from django.db.models import Q

# Create your views here.

def SearchResult(request):
    products = None
    query = None

    try:
        if 'q' in request.GET:
            query = request.GET.get('q')
            products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    except Exception as e:
        # Handle the exception (e.g., log it or render an error page)
        print(f"An error occurred: {e}")
        products = None  # Set products to None to indicate an error

    return render(request, 'search.html', {'query': query, 'products': products})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>

        <script src="{% static 'js/popper.min.js' %}" ></script>
        <script src="{% static 'js/bootstrap.min.js' %}" ></script>
        <script src="https://kit.fontawesome.com/5b4ee1d6bc.js" crossorigin="anonymous"></script>


</body>
{% include 'footer.html' %}
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        This is the Cart Page.
        Proceed to review your items and place the order
{% endblock %}

{% block title %}
    Cart - XPAIN SHOPPE PVT LTD
{% endblock %}
{% block content %}

    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">Your Shopping Cart is Empty</h1>
                <br>
                <p class="text-center">Please Click <a href="{% url 'ecommerceapp:allProdCat' %}">Here </a>to Continue Shopping.. </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">Your Shopping Cart</h1>
                <br>
            </div>
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th colspan="5">
                                    Your Items
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}
                                <tr>
                                    <td>
                                        <a href="{{ product_detail_url }}"><img src="{{ cart_item.product.image.url }}" height="100px" width="100px" style="object-fit: contain" alt="" class="float-left rounded custom_image"> </a>

                                    </td>
                                    <td class="text-left" style="text-align: left">
                                        {{ cart_item.product.name }}
                                        <br>
                                        Price: ${{ cart_item.product.price }}
                                        <br>
                                        Qty : {{ cart_item.quantity }} x $ {{ cart_item.product.name }}
                                    </td>
                                    <td>
                                        $ {{ cart_item.sub_total }}
                                    </td>
                                    {% if cart_item.quantity < cart_item.product.stock %}
                                        <td>
                                            <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                                            &nbsp;
                                            <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                            &nbsp;
                                            <a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                                        </td>
                                    {% else %}
                                        <td>
                                            &nbsp;
                                            <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                            &nbsp;
                                            <a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                                        </td>
                                    {% endif %}

                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <th>
                        CHECKOUT
                    </th>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please Review Your Shopping Cart Items Before Proceeding With the Order Payment..
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            Your Total is : <strong>{{ total }}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-outline-success btn-block my_custom_button">Continue Shopping</a>
            </div>
        </div>
        </div>
        {% endif %}
</div>
    <br>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to XPAIN SHOPPE where you can buy different items....
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - XPAIN SHOPPE
    {% else %}
       See our New Collections - Xpain Shoppe
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><a class="btn btn-outline-warning" href="{% url 'ecommerceapp:allProdCat' %}">Our Product Collections >></a> </p>
            </div>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
    </div>
            <br>
    <div>
            <h1 class="text-center my_title" >{{ category.name }}</h1>
            <p class="text-justify">{{ category.description }}</p>
    </div>
        {% else %}
            <br>
            <div>
            <img class="my_image my_image_padding" src="{% static 'img/shop_banner.png' %}" alt="our products" height="400px" width="1200px">
            </div>
            <br>
            <br>
            <div>
                <h1 class="text-center my_title" style="font-weight: bold; font-size: 30px">Our Products Collections</h1>
                <p class="text-justify product_para">Welcome to our curated world of possibilities – Explore our meticulously crafted collections, where every product tells a unique story. Our ecommerce platform showcases a thoughtfully assembled selection that transcends mere merchandise; it's a celebration of style, functionality, and quality. Dive into a symphony of choices, from timeless classics to the latest trends, each item handpicked to elevate your experience.<br><br>
                Discover the essence of innovation and craftsmanship as you navigate through our meticulously organized product collections. From fashion-forward apparel to cutting-edge electronics, home essentials to lifestyle accessories, our diverse range caters to every taste and requirement.<br><br>
                Our commitment to excellence is evident in every product, ensuring that you not only receive a purchase but an investment in quality and satisfaction. Whether you're seeking the latest in technology, timeless fashion pieces, or functional everyday items, our collections are designed to inspire and enrich your life.<br><br>
                Experience the convenience of online shopping with our user-friendly interface, secure transactions, and prompt delivery. Join us in exploring a world where every product is a testament to our dedication to providing you with the finest selections, all conveniently gathered in our thoughtfully curated collections.</p>
            </div>
            <br>
            <br>
        {% endif %}
    <div>
        <div>
        <br>
        <div class="container">
            <div class="row mx_auto">
            {% for prod in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width: 10rem;  margin-bottom: 15px">
                        <a href="{{ prod.get_url }}"><img src="{{ prod.image.url }}" alt="{{ prod.name }}" style="height: 200px;object-fit: contain" class="card-img-top my_image"> </a>
                    <div class="card-body">

                        <h4>{{ prod.name }}</h4>
                        <p>${{ prod.price }}</p>
                    </div>
                    </div>
                </div>
                <br>

            {% endfor %}
        </div>
        <div class="mx-auto">

            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{ pg }}</a>
                {% endfor %}
            </div>
        {% endif %}
        </div>
        <br>
        </div>
        </div>
    </div>
    </div>
    <br><br>
{% endblock %}

ecommerce/templates/footer.html
<footer class="mt-auto">
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">
        &copy; XPAIN SHOPPE pvt ltd. All rights reserved
    </p>
</div>
</footer>

ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:allProdCat'%}" ><img src="{% static 'img/xpain_logo.png' %}" alt="logimage" height="70px" width="200px"></a>
    </center>
</header>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecommerceapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a href="{% url 'ecommerceapp:allProdCat' %}" class="dropdown-item">All Products</a></li>
            <li>{% for link in links %}
            <li><a href="{{ link.get_url }}" class="dropdown-item">{{ link.name }}</a>
            {% endfor %}</li>
            <li><hr class="dropdown-divider" class="dropdown-item"></li>
            <li class="dropdown-item">Your Cart()</li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{ item_count }})</a>
        </li>
      {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.description|truncatewords:155 }}
        Welcome to XPAIN SHOPPE where you can buy different items....
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} - XPAIN SHOPPE
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row my_prod_row_class">
        <div class="mx-auto" style="text-align: end">
            <p><a href="{% url 'ecommerceapp:allProdCat' %}" style="text-decoration: none;font-size: 14px">HOME</a> | <a href="{{ product.category }}" style="text-decoration: none;font-size: 14px" >{{ product.name }}</a>  </p>
        </div>
    <div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width: 18rem">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" width="300px" height="300px" style="object-fit: contain">
            </div>
    </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
            <div>
                <h1 class="my_prod_title">{{ product.name }}</h1>
                <p>${{ product.price }}</p>
                <p style="font-size: 20px;font-weight: bold" >Product Description</p>
                <p>{{ product.description }}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify prod_stock"><b>Out of Stock</b></p>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'cart_app:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
    </div>
            </div>
        </div>
    </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.description|truncatewords:155 }}
        We have variety of products .
{% endblock %}

{% block title %}
    Search
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">You have searcher for :<b>{{ query }}</b></p>

    </div>
    <div class="container">
            <div class="row mx_auto">
            {% for prod in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width: 10rem;  margin-bottom: 15px">
                        <a href="{{ prod.get_url }}"><img src="{{ prod.image.url }}" alt="{{ prod.name }}" style="height: 200px;object-fit: contain" class="card-img-top my_image"> </a>
                    <div class="card-body">

                        <h4>{{ prod.name }}</h4>
                        <p>${{ prod.price }}</p>
                    </div>
                    </div>

    </div>

    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text"> 0 Results Found</p>

    </div>
            {% endfor %}
    </div>
</div>

{% endblock %}